spring:
  application:
    name: ApiRestaurant

  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:14071/railway
    username: root
    password: YWdZtdDmyqsedhiOXbpzMEFHMHkvQtWG
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none    # o "none" si no quieres que Spring cree/actualice tablas automáticamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true